# Fallback servers. Will attempt to send to all listed servers in order until one is successful.
fallbackServers:
  - lobby
  - hub
  - limbo

# Will not attempt to send the player to a fallback server if their kick reason matches any of these regexes.
blacklistedMessages:
  - ".*banned.*"

# Will not attempt to send the player to a fallback server if they were kicked from a server in this list.
blacklistedServers:
  - test